const ACTION_TYPES = {
  // AUTH
  AUTH_START: 'AUTH_START',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_ERROR: 'AUTH_ERROR',
  RESET_AUTH_ERROR: 'RESET_AUTH_ERROR',
  RESET_AUTH_STATE: 'RESET_AUTH_STATE',

  // ACCOUNT
  SET_ACCOUNT_INFO: 'SET_ACCOUNT_INFO',
  UPDATE_INFO_START: 'UPDATE_INFO_START',
  UPDATE_INFO_SUCCESS: 'UPDATE_INFO_SUCCESS',
  UPDATE_INFO_ERROR: 'UPDATE_INFO_ERROR',
  RESET_UPDATE_INFO_STATE: 'RESET_UPDATE_INFO_STATE',
  RESET_ACCOUNT_STATE: 'RESET_ACCOUNT_STATE',
};

export default ACTION_TYPES;
